### ISSUE TITLE
ox => oxes

### ISSUE THREAD

**Issue by ErikEJ** [sarathkcm/Pluralize.NET#10]
"HugeOx", "HugeOxen", but got "HugeOxes" (could be an edge case)

**Comment by sarathkcm** [comment]
As @jespersh commented in the referenced issue, Pluralize.NET is for single English words.  

Still when you pluralize 'HugeCactus' you get 'HugeCacti' and with 'HugeBull' you get 'HugeBulls'. This is because these words follow general rules of pluralizing. The word 'ox' is one of the special cases, and the library keeps a list of special cases and their plural forms to help convert them. 

It's impractical to keep a list of all possible combinations, and therefore as long as you throw a single word at it, the library should be able to convert it correctly.

If you have the phrase in PascalCase, why not split and pluralize only the last word? Just a suggestion.

**Comment by sarathkcm** [comment]
@ErikEJ I'm closing this issue, as this is beyond the scope of this library. Please free feel to comment or re-open if you have any suggestions or anything to discuss.
